parameters:
    swm.mail_hook.api_service.campainmonitor.class: Swm\Bundle\MailHookBundle\ApiService\CampainmonitorApiService
    swm.mail_hook.api_service.mailgun.class: Swm\Bundle\MailHookBundle\ApiService\MailgunApiService
    swm.mail_hook.api_service.mailjet.class: Swm\Bundle\MailHookBundle\ApiService\MailjetApiService
    swm.mail_hook.api_service.mandrill.class: Swm\Bundle\MailHookBundle\ApiService\MandrillApiService
    swm.mail_hook.api_service.sendgrid.class: Swm\Bundle\MailHookBundle\ApiService\SendgridApiService
    swm.mail_hook.api_service.sparkpost.class: Swm\Bundle\MailHookBundle\ApiService\SparkpostApiService
    swm.mail_hook.api_service.ses.class: Swm\Bundle\MailHookBundle\ApiService\SesApiService

services:
    swm.mail_hook.api_service.campainmonitor:
        class: "%swm.mail_hook.api_service.campainmonitor.class%"
        tags:
            -  { name: swm.mailhook, alias: campainmonitor }

    swm.mail_hook.api_service.mailgun:
        class: "%swm.mail_hook.api_service.mailgun.class%"
        tags:
            -  { name: swm.mailhook, alias: mailgun }

    swm.mail_hook.api_service.mailjet:
        class: "%swm.mail_hook.api_service.mailjet.class%"
        tags:
            -  { name: swm.mailhook, alias: mailjet }

    swm.mail_hook.api_service.mandrill:
        class: "%swm.mail_hook.api_service.mandrill.class%"
        tags:
            -  { name: swm.mailhook, alias: mandrill }

    swm.mail_hook.api_service.sendgrid:
        class: "%swm.mail_hook.api_service.sendgrid.class%"
        tags:
            -  { name: swm.mailhook, alias: sendgrid }

    swm.mail_hook.api_service.sparkpost:
        class: "%swm.mail_hook.api_service.sparkpost.class%"
        tags:
            -  { name: swm.mailhook, alias: sparkpost }

    swm.mail_hook.api_service.ses:
        class: "%swm.mail_hook.api_service.ses.class%"
        tags:
            -  { name: swm.mailhook, alias: ses }